export const JOBS_DATA = [
  {
    job_id: "001",
    clinic_id: "C101",
    posted_date: "2024-01-01",
    organization_type: "Hospital",
    job_function: "Nurse",
    work_location: "New York",
    vacancies: "5",
    shift: "Morning",
    salary_range: "$40000 - $50000",
    job_description: "Provide patient care and support.",
    qualification: "Bachelor's in Nursing",
    experience_required: "2 years",
    key_skills: "Patient care, Communication",
  },
  {
    job_id: "002",
    clinic_id: "C102",
    posted_date: "2024-01-05",
    organization_type: "Clinic",
    job_function: "General Practitioner",
    work_location: "Los Angeles",
    vacancies: "2",
    shift: "Evening",
    salary_range: "$70000 - $80000",
    job_description: "Conduct routine check-ups.",
    qualification: "MD in General Medicine",
    experience_required: "5 years",
    key_skills: "Diagnosis, Patient management",
  },
  {
    job_id: "003",
    clinic_id: "C103",
    posted_date: "2024-01-10",
    organization_type: "Dental Clinic",
    job_function: "Dentist",
    work_location: "Chicago",
    vacancies: "3",
    shift: "Day",
    salary_range: "$60000 - $70000",
    job_description: "Perform dental procedures.",
    qualification: "DDS",
    experience_required: "3 years",
    key_skills: "Dentistry, Patient comfort",
  },
  {
    job_id: "004",
    clinic_id: "C104",
    posted_date: "2024-01-15",
    organization_type: "Specialty Hospital",
    job_function: "Cardiologist",
    work_location: "Houston",
    vacancies: "1",
    shift: "Rotating",
    salary_range: "$120000 - $150000",
    job_description: "Treat heart conditions.",
    qualification: "MD in Cardiology",
    experience_required: "10 years",
    key_skills: "Cardiology, Emergency response",
  },
  {
    job_id: "005",
    clinic_id: "C105",
    posted_date: "2024-01-20",
    organization_type: "Rehabilitation Center",
    job_function: "Physical Therapist",
    work_location: "Miami",
    vacancies: "4",
    shift: "Full Time",
    salary_range: "$50000 - $60000",
    job_description: "Assist in patient recovery.",
    qualification: "Masters in Physical Therapy",
    experience_required: "1 year",
    key_skills: "Rehabilitation, Exercise Therapy",
  },
];
