import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'


const nunito = localFont({
  src: '../../public/fonts/Nunito-VariableFont_wght.ttf',
  display: 'swap',
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
